### ISSUE TITLE
Betaalverzoek is verlopen

### ISSUE THREAD

**Issue by legende11** [kloentje2/FiveM-MEOS#3]

**Comment by kloentje2** [comment]
Hoi legende,

Ik plaats een nieuwe en deel deze hier ook met jou.

Hoi, wil je mij betalen voor MEOS donatie? Het bedrag mag je zelf kiezen. Je kunt met elke bank in Nederland betalen. Dank je wel!
https://betaalverzoek.rabobank.nl/betaalverzoek/?id=A8-pTEc9T72h0blzCQN5UA
